# agnoster like theme

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#003541)\
$os\
$username\
[](bg:#2472C8 fg:#003541)\
$directory\
[](fg:#2472C8 bg:#E5E510)\
$git_branch\
$git_status\
[](fg:#E5E510 bg:#B7B70A)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#B7B70A bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#29577A)\
$cmd_duration\
$status\
$time
[>](#003541) \
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#003541"
style_root = "bg:#003541"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#003541 fg:#FFFFFF"
disabled = true                 # Disabled by default

[directory]
style = "bg:#2472C8 fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#A4A40D fg:#000000"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#E5E510 fg:#000000"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#E5E510 fg:#000000"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#B7B70A fg:#000000"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
style = "bg:#29577A"
format = '[ ⏳  $duration]($style)'
min_time = 1000
show_milliseconds = true
min_time_to_notify = 20000
show_notifications = true

[status]
disabled = false
format = '[ $symbol $common_meaning$signal_name$maybe_int ]($style)[](fg:#29577A) '
style = 'bg:#29577A'
success_symbol = " "
map_symbol = true
